image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        script:
          - echo "Pipeline Init"
          - apt-get update
          - apt-get -qq install git-ftp
          - echo "Pushing"
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_HOST
          - echo "Done Pushing"
