image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        script:
          - echo "Pipeline Init"
          - apt-get update
          - apt-get -qq install git-ftp
          - echo "Initiating Push"
          - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://kakicg.xsrv.jp/cgkojo.com/public_html/haruguchi
          - echo "Done Pushing"
